// Naruto: Shinobi Clash - Complete Combat Engine & Fighter Mechanics

class Fighter {
    constructor(config, isPlayer2 = false, isAI = false) {
        this.charData = config;
        this.id = config.id;
        this.name = config.name;
        this.isPlayer2 = isPlayer2;
        this.isAI = isAI;

        // Position & Physics
        this.width = 64;
        this.height = 110;
        this.x = isPlayer2 ? 820 : 180;
        this.y = 380;
        this.vx = 0;
        this.vy = 0;
        this.facing = isPlayer2 ? -1 : 1;
        this.isGrounded = false;

        // Stats
        this.maxHp = config.maxHp;
        this.hp = config.maxHp;
        this.maxChakra = config.maxChakra;
        this.chakra = 40;
        this.speed = config.speed;
        this.jumpForce = config.jumpForce;
        this.attackPower = config.attackPower;

        // Combat State
        this.state = 'idle'; // idle, run, jump, light_atk, heavy_atk, guard, dash, casting, hurt, dead
        this.stateTime = 0;
        this.comboStep = 0;
        this.comboTimer = 0;
        this.hitStun = 0;
        this.isGuarding = false;
        this.isCharging = false;
        this.invulnerableTime = 0;

        // Cooldowns
        this.kawarimiCooldown = 0;
        this.jutsuCooldowns = [0, 0, 0]; // Jutsu 1, Jutsu 2, Ultimate

        // Active Jutsus & Projectiles
        this.activeAttacks = []; // Hitboxes generated by attacks
        this.activeProjectiles = []; // Fireball, bunshin, etc.
        this.awakeningActive = false;
        this.awakeningTimer = 0;

        // Animation frame
        this.animFrame = 0;
        this.walkCycle = 0;

        // AI specific
        this.aiThinkTimer = 0;
        this.aiAction = 'idle';
    }

    update(dt, opponent, particleSys, soundCtrl, arenaBounds) {
        // Timers update
        this.stateTime += dt;
        if (this.hitStun > 0) this.hitStun -= dt;
        if (this.invulnerableTime > 0) this.invulnerableTime -= dt;
        if (this.kawarimiCooldown > 0) this.kawarimiCooldown -= dt;
        for (let i = 0; i < this.jutsuCooldowns.length; i++) {
            if (this.jutsuCooldowns[i] > 0) this.jutsuCooldowns[i] -= dt;
        }

        // Passive regen
        if (this.id === 'naruto' && this.hp < this.maxHp * 0.3) {
            this.hp = Math.min(this.maxHp, this.hp + 0.15);
        }
        if (this.id === 'kakashi') {
            this.chakra = Math.min(this.maxChakra, this.chakra + 0.08);
        }

        // Awakening timer
        if (this.awakeningActive) {
            this.awakeningTimer -= dt;
            particleSys.createChakraFlame(this.x + this.width / 2, this.y + this.height * 0.6, '#ffeb3b', this.vx);
            if (this.awakeningTimer <= 0) {
                this.awakeningActive = false;
            }
        }

        // Facing direction auto-align when not attacking
        if (this.state === 'idle' || this.state === 'run' || this.state === 'jump') {
            if (opponent && !this.isDead()) {
                this.facing = opponent.x > this.x ? 1 : -1;
            }
        }

        // Chakra charging state
        if (this.isCharging && this.isGrounded && this.state === 'idle') {
            this.chakra = Math.min(this.maxChakra, this.chakra + 0.5);
            particleSys.createChakraFlame(this.x + this.width / 2, this.y + this.height * 0.7, this.charData.auraColor, 0);
            if (Math.random() < 0.2) {
                soundCtrl.playChakraCharge();
            }
        }

        // Hit stun handling
        if (this.hitStun > 0) {
            this.state = 'hurt';
            this.vx *= 0.85;
        } else if (this.state === 'hurt') {
            this.state = 'idle';
        }

        // Apply Physics
        this.vy += 0.65; // Gravity
        this.x += this.vx;
        this.y += this.vy;

        // Ground collision (ground level at 470px)
        const groundY = arenaBounds.groundY - this.height;
        if (this.y >= groundY) {
            this.y = groundY;
            this.vy = 0;
            this.isGrounded = true;
            if (this.state === 'jump') this.state = 'idle';
        } else {
            this.isGrounded = false;
        }

        // Wall bounds
        if (this.x < arenaBounds.minX) {
            this.x = arenaBounds.minX;
            this.vx = 0;
        }
        if (this.x + this.width > arenaBounds.maxX) {
            this.x = arenaBounds.maxX - this.width;
            this.vx = 0;
        }

        // Friction on ground
        if (this.isGrounded && this.state !== 'run' && this.state !== 'dash') {
            this.vx *= 0.7;
        }

        // Animation update
        this.animFrame++;
        if (this.state === 'run') {
            this.walkCycle += 0.2;
        }

        // Attack state timeout
        if (this.state === 'light_atk' && this.stateTime > 0.22) {
            this.state = 'idle';
        }
        if (this.state === 'heavy_atk' && this.stateTime > 0.38) {
            this.state = 'idle';
        }
        if (this.state === 'dash' && this.stateTime > 0.2) {
            this.state = 'idle';
            this.vx = 0;
        }
        if (this.state === 'casting' && this.stateTime > 0.45) {
            this.state = 'idle';
        }

        // Update Projectiles & Summons
        for (let i = this.activeProjectiles.length - 1; i >= 0; i--) {
            const proj = this.activeProjectiles[i];
            proj.update(dt, opponent, particleSys, soundCtrl);
            if (proj.isFinished) {
                this.activeProjectiles.splice(i, 1);
            }
        }

        // Update Active Attack Hitboxes
        for (let i = this.activeAttacks.length - 1; i >= 0; i--) {
            const atk = this.activeAttacks[i];
            atk.duration -= dt;
            if (atk.duration <= 0) {
                this.activeAttacks.splice(i, 1);
                continue;
            }

            // Check collision with opponent
            if (opponent && !opponent.isDead() && opponent.invulnerableTime <= 0) {
                if (this.checkCollision(atk.box, opponent.getHitbox())) {
                    this.executeHit(atk, opponent, particleSys, soundCtrl);
                    this.activeAttacks.splice(i, 1);
                }
            }
        }

        // AI Routine if enabled
        if (this.isAI && !this.isDead()) {
            this.updateAI(dt, opponent, soundCtrl);
        }
    }

    // AI Decision Making
    updateAI(dt, opponent, soundCtrl) {
        if (!opponent || opponent.isDead() || this.hitStun > 0) return;

        this.aiThinkTimer += dt;
        const dist = Math.abs((this.x + this.width / 2) - (opponent.x + opponent.width / 2));
        const opponentAttacking = opponent.state === 'light_atk' || opponent.state === 'heavy_atk' || opponent.state === 'casting';

        // React to incoming attacks with Kawarimi / Guard
        if (opponentAttacking && dist < 120 && Math.random() < 0.25 && this.kawarimiCooldown <= 0) {
            this.triggerKawarimi(soundCtrl);
            return;
        }

        if (this.aiThinkTimer > 0.22) {
            this.aiThinkTimer = 0;

            // Strategy based on distance and chakra
            if (this.chakra >= 100 && Math.random() < 0.45) {
                // Try Ultimate!
                this.triggerJutsu(2, soundCtrl);
                return;
            }

            if (dist > 350) {
                // Long range: Fireball, Bunshin, or Charge Chakra
                if (this.chakra < 40 && Math.random() < 0.5) {
                    this.isCharging = true;
                } else if (this.chakra >= 25 && Math.random() < 0.4) {
                    this.isCharging = false;
                    this.triggerJutsu(0, soundCtrl); // Fireball / Clones
                } else {
                    this.isCharging = false;
                    this.move(this.facing, 1); // Dash closer
                }
            } else if (dist > 140) {
                // Mid range: Chidori / Rasengan or approach
                this.isCharging = false;
                if (this.chakra >= 40 && Math.random() < 0.5) {
                    this.triggerJutsu(1, soundCtrl); // Rasengan / Chidori
                } else {
                    this.move(this.facing, 1);
                }
            } else {
                // Close melee range
                this.isCharging = false;
                if (Math.random() < 0.35) {
                    this.lightAttack(soundCtrl);
                } else if (Math.random() < 0.3) {
                    this.heavyAttack(soundCtrl);
                } else if (Math.random() < 0.2) {
                    this.guard(true);
                    setTimeout(() => this.guard(false), 400);
                } else {
                    this.jump();
                }
            }
        }
    }

    // Input Actions
    move(dir, factor = 1) {
        if (this.state === 'hurt' || this.state === 'casting' || this.isDead()) return;
        this.isCharging = false;
        this.vx = dir * this.speed * factor;
        this.facing = dir;
        if (this.isGrounded && this.state !== 'light_atk' && this.state !== 'heavy_atk') {
            this.state = 'run';
        }
    }

    stopMove() {
        if (this.state === 'run') {
            this.state = 'idle';
            this.vx = 0;
        }
    }

    jump() {
        if (!this.isGrounded || this.state === 'hurt' || this.isDead()) return;
        this.isCharging = false;
        this.vy = -this.jumpForce;
        this.isGrounded = false;
        this.state = 'jump';
    }

    guard(isGuarding) {
        if (this.state === 'hurt' || this.isDead()) return;
        this.isGuarding = isGuarding;
        if (isGuarding) {
            this.state = 'guard';
            this.vx = 0;
        } else if (this.state === 'guard') {
            this.state = 'idle';
        }
    }

    startCharge() {
        if (this.isGrounded && !this.isDead() && this.state === 'idle') {
            this.isCharging = true;
        }
    }

    stopCharge() {
        this.isCharging = false;
    }

    // Basic Light Attack (Kunai combo)
    lightAttack(soundCtrl) {
        if (this.state === 'hurt' || this.state === 'casting' || this.isDead()) return;
        this.isCharging = false;
        this.state = 'light_atk';
        this.stateTime = 0;
        this.comboStep = (this.comboStep + 1) % 3;

        soundCtrl.playWhoosh();
        // Attack Box in front of character
        const boxWidth = 55;
        const boxX = this.facing === 1 ? this.x + this.width : this.x - boxWidth;
        this.activeAttacks.push({
            box: { x: boxX, y: this.y + 20, width: boxWidth, height: 50 },
            damage: 28 * this.attackPower,
            knockbackX: this.facing * 4,
            knockbackY: -2,
            duration: 0.16,
            isHeavy: false
        });
    }

    // Heavy Attack (Taijutsu kick)
    heavyAttack(soundCtrl) {
        if (this.state === 'hurt' || this.state === 'casting' || this.isDead()) return;
        this.isCharging = false;
        this.state = 'heavy_atk';
        this.stateTime = 0;

        soundCtrl.playWhoosh();
        const boxWidth = 65;
        const boxX = this.facing === 1 ? this.x + this.width : this.x - boxWidth;
        this.activeAttacks.push({
            box: { x: boxX, y: this.y + 15, width: boxWidth, height: 60 },
            damage: 55 * this.attackPower,
            knockbackX: this.facing * 10,
            knockbackY: -6,
            duration: 0.25,
            isHeavy: true
        });
    }

    // Kawarimi (Substitution Log / Ninja Teleport Dodge)
    triggerKawarimi(soundCtrl) {
        if (this.kawarimiCooldown > 0 || this.isDead()) return false;
        this.kawarimiCooldown = this.id === 'sasuke' ? 2.5 : 3.5;
        soundCtrl.playKawarimi();

        // Teleport behind or evasive jump
        const teleportDist = this.facing === 1 ? -120 : 120;
        this.x += teleportDist;
        this.invulnerableTime = 0.5;
        this.hitStun = 0;
        this.state = 'idle';
        return true;
    }

    // Jutsu Casting (0: Jutsu 1, 1: Jutsu 2, 2: Ultimate)
    triggerJutsu(index, soundCtrl) {
        if (this.state === 'hurt' || this.isDead()) return false;
        const jutsu = this.charData.jutsus[index];
        if (!jutsu) return false;

        if (this.chakra < jutsu.cost) {
            return false; // Not enough chakra!
        }
        if (this.jutsuCooldowns[index] > 0) {
            return false; // Cooldown not ready!
        }

        this.chakra -= jutsu.cost;
        this.jutsuCooldowns[index] = jutsu.cooldown;
        this.state = 'casting';
        this.stateTime = 0;
        this.isCharging = false;

        // Execute specific jutsu logic
        this.spawnJutsuEffect(jutsu, soundCtrl);
        return true;
    }

    spawnJutsuEffect(jutsu, soundCtrl) {
        const dir = this.facing;
        const spawnX = dir === 1 ? this.x + this.width + 10 : this.x - 50;
        const spawnY = this.y + 25;

        // Naruto Jutsus
        if (this.id === 'naruto') {
            if (jutsu.id === 'bunshin') {
                soundCtrl.playKawarimi();
                // Spawn 2 Shadow Clones rushing
                this.activeProjectiles.push(new ShadowClone(this.x + dir * 30, this.y, dir, this.attackPower));
                setTimeout(() => {
                    this.activeProjectiles.push(new ShadowClone(this.x + dir * 60, this.y, dir, this.attackPower));
                }, 180);
            } else if (jutsu.id === 'rasengan') {
                soundCtrl.playRasengan();
                this.vx = dir * 16; // Rapid dash
                this.activeAttacks.push({
                    box: { x: this.x + dir * 30, y: this.y + 10, width: 80, height: 70 },
                    damage: jutsu.damage * this.attackPower,
                    knockbackX: dir * 18,
                    knockbackY: -8,
                    duration: 0.35,
                    isHeavy: true,
                    type: 'rasengan'
                });
            } else if (jutsu.id === 'ultimate_rasenshuriken') {
                soundCtrl.playUltimateAwakening();
                this.awakeningActive = true;
                this.awakeningTimer = 8.0;
                this.activeProjectiles.push(new Rasenshuriken(spawnX, spawnY - 10, dir, jutsu.damage));
            }
        }

        // Sasuke Jutsus
        else if (this.id === 'sasuke') {
            if (jutsu.id === 'fireball') {
                soundCtrl.playFireball();
                this.activeProjectiles.push(new Fireball(spawnX, spawnY, dir, jutsu.damage));
            } else if (jutsu.id === 'chidori') {
                soundCtrl.playChidori();
                this.vx = dir * 18; // Super fast dash
                this.activeAttacks.push({
                    box: { x: this.x + dir * 40, y: this.y + 10, width: 90, height: 70 },
                    damage: jutsu.damage * this.attackPower,
                    knockbackX: dir * 19,
                    knockbackY: -7,
                    duration: 0.32,
                    isHeavy: true,
                    type: 'chidori'
                });
            } else if (jutsu.id === 'ultimate_kirin') {
                soundCtrl.playUltimateAwakening();
                this.activeProjectiles.push(new KirinDragon(spawnX + dir * 120, 100, dir, jutsu.damage));
            }
        }

        // Kakashi Jutsus
        else if (this.id === 'kakashi') {
            if (jutsu.id === 'mudwall') {
                soundCtrl.playHit(true);
                this.activeProjectiles.push(new EarthWall(spawnX + dir * 60, this.y + 20, dir, jutsu.damage));
            } else if (jutsu.id === 'raikiri') {
                soundCtrl.playChidori();
                this.vx = dir * 20;
                this.activeAttacks.push({
                    box: { x: this.x + dir * 40, y: this.y + 10, width: 90, height: 70 },
                    damage: jutsu.damage * this.attackPower,
                    knockbackX: dir * 20,
                    knockbackY: -8,
                    duration: 0.3,
                    isHeavy: true,
                    type: 'raikiri'
                });
            } else if (jutsu.id === 'ultimate_kamui') {
                soundCtrl.playUltimateAwakening();
                this.activeProjectiles.push(new KamuiVortex(spawnX + dir * 150, this.y - 10, dir, jutsu.damage));
            }
        }

        // Itachi Jutsus
        else if (this.id === 'itachi') {
            if (jutsu.id === 'crow_clone') {
                soundCtrl.playKawarimi();
                this.activeProjectiles.push(new CrowFlock(this.x, this.y, dir, jutsu.damage));
            } else if (jutsu.id === 'amaterasu') {
                soundCtrl.playFireball();
                this.activeProjectiles.push(new AmaterasuFlame(spawnX + dir * 140, this.y, dir, jutsu.damage));
            } else if (jutsu.id === 'ultimate_tsukuyomi') {
                soundCtrl.playUltimateAwakening();
                this.activeProjectiles.push(new TsukuyomiDimension(spawnX + dir * 100, this.y, dir, jutsu.damage));
            }
        }
    }

    // Execute Hit on target
    executeHit(atk, target, particleSys, soundCtrl) {
        let finalDamage = atk.damage;
        const isGuarding = target.isGuarding && ((target.facing === 1 && this.x > target.x) || (target.facing === -1 && this.x < target.x));

        if (isGuarding) {
            finalDamage *= 0.22; // Guard reduces 78% damage!
            soundCtrl.playClash();
            particleSys.createHitSparks(target.x + target.width / 2, target.y + target.height / 2, '#4fc3f7', 10);
            particleSys.addDamageNumber(target.x + target.width / 2, target.y, Math.round(finalDamage) + ' (GUARD)', false);
            target.vx = atk.knockbackX * 0.3;
        } else {
            soundCtrl.playHit(atk.isHeavy);
            particleSys.createHitSparks(target.x + target.width / 2, target.y + target.height / 2, atk.isHeavy ? '#ff1744' : '#ffeb3b', 22);
            particleSys.addDamageNumber(target.x + target.width / 2, target.y, Math.round(finalDamage), atk.isHeavy);
            
            target.hitStun = atk.isHeavy ? 0.38 : 0.2;
            target.vx = atk.knockbackX;
            target.vy = atk.knockbackY;
        }

        target.hp = Math.max(0, target.hp - finalDamage);
        // Gain small chakra on hit
        this.chakra = Math.min(this.maxChakra, this.chakra + (atk.isHeavy ? 10 : 5));

        if (target.hp <= 0) {
            target.state = 'dead';
            soundCtrl.playHit(true);
        }
    }

    getHitbox() {
        return {
            x: this.x + 10,
            y: this.y,
            width: this.width - 20,
            height: this.height
        };
    }

    checkCollision(rect1, rect2) {
        return (
            rect1.x < rect2.x + rect2.width &&
            rect1.x + rect1.width > rect2.x &&
            rect1.y < rect2.y + rect2.height &&
            rect1.y + rect1.height > rect2.y
        );
    }

    isDead() {
        return this.hp <= 0;
    }

    // --- CANVAS RENDERING (Stylized High-Definition Anime Ninja) ---
    render(ctx) {
        ctx.save();

        const centerX = this.x + this.width / 2;
        const bottomY = this.y + this.height;

        // 1. Ground Shadow
        ctx.fillStyle = 'rgba(0, 0, 0, 0.45)';
        ctx.beginPath();
        ctx.ellipse(centerX, bottomY - 3, 28, 8, 0, 0, Math.PI * 2);
        ctx.fill();

        // 2. Invulnerability blink
        if (this.invulnerableTime > 0 && Math.floor(Date.now() / 60) % 2 === 0) {
            ctx.restore();
            return;
        }

        // 3. Render Projectiles
        for (let proj of this.activeProjectiles) {
            proj.render(ctx);
        }

        // 4. Character Body Rendering
        ctx.translate(centerX, this.y);
        ctx.scale(this.facing, 1);

        // Guard Shield Aura
        if (this.isGuarding) {
            ctx.strokeStyle = 'rgba(79, 195, 247, 0.85)';
            ctx.lineWidth = 4;
            ctx.shadowColor = '#00e5ff';
            ctx.shadowBlur = 15;
            ctx.beginPath();
            ctx.arc(15, 55, 50, -Math.PI * 0.4, Math.PI * 0.4);
            ctx.stroke();
        }

        // Draw Stylized Ninja Figure
        this.drawNinjaFigure(ctx);

        ctx.restore();
    }

    drawNinjaFigure(ctx) {
        const t = this.walkCycle;
        const isRun = this.state === 'run';
        const isLight = this.state === 'light_atk';
        const isHeavy = this.state === 'heavy_atk';
        const isHurt = this.state === 'hurt';
        const isDead = this.isDead();

        // Legs
        const legOffset = isRun ? Math.sin(t) * 16 : 0;
        ctx.lineWidth = 9;
        ctx.lineCap = 'round';

        // Pants Color
        let pantsColor = '#1a237e'; // Naruto orange top with blue pants
        if (this.id === 'naruto') pantsColor = '#e65100';
        if (this.id === 'sasuke') pantsColor = '#212121';
        if (this.id === 'kakashi') pantsColor = '#1a237e';
        if (this.id === 'itachi') pantsColor = '#1b1b1b';

        ctx.strokeStyle = pantsColor;

        // Left Leg
        ctx.beginPath();
        ctx.moveTo(-10, 60);
        ctx.lineTo(-12 - legOffset, 95);
        ctx.lineTo(-14 - legOffset, 108);
        ctx.stroke();

        // Right Leg
        ctx.beginPath();
        ctx.moveTo(10, 60);
        ctx.lineTo(12 + legOffset, 95);
        ctx.lineTo(14 + legOffset, 108);
        ctx.stroke();

        // Ninja Sandals
        ctx.strokeStyle = '#212121';
        ctx.lineWidth = 10;
        ctx.beginPath();
        ctx.moveTo(-18 - legOffset, 108);
        ctx.lineTo(-6 - legOffset, 108);
        ctx.moveTo(8 + legOffset, 108);
        ctx.lineTo(20 + legOffset, 108);
        ctx.stroke();

        // Torso / Jacket
        let outfitColor = '#ff9800';
        if (this.id === 'naruto') outfitColor = '#ff9800';
        if (this.id === 'sasuke') outfitColor = '#1a237e';
        if (this.id === 'kakashi') outfitColor = '#2e7d32'; // Green Flak jacket
        if (this.id === 'itachi') outfitColor = '#121212'; // Akatsuki cloak

        ctx.fillStyle = outfitColor;
        ctx.beginPath();
        ctx.roundRect(-16, 26, 32, 40, 6);
        ctx.fill();

        // Akatsuki Red Clouds on Itachi
        if (this.id === 'itachi') {
            ctx.fillStyle = '#d50000';
            ctx.beginPath();
            ctx.arc(-2, 40, 7, 0, Math.PI * 2);
            ctx.arc(6, 42, 6, 0, Math.PI * 2);
            ctx.arc(3, 36, 5, 0, Math.PI * 2);
            ctx.fill();
        }

        // Kakashi Flak Vest pockets
        if (this.id === 'kakashi') {
            ctx.fillStyle = '#1b5e20';
            ctx.fillRect(-12, 38, 10, 12);
            ctx.fillRect(2, 38, 10, 12);
        }

        // Arms & Weapon
        ctx.strokeStyle = outfitColor;
        ctx.lineWidth = 8;
        const armSwing = isLight ? 25 : (isHeavy ? 35 : (isRun ? Math.sin(t) * 15 : 0));

        // Back Arm
        ctx.beginPath();
        ctx.moveTo(-12, 32);
        ctx.lineTo(-20 - armSwing * 0.5, 48);
        ctx.lineTo(-15, 60);
        ctx.stroke();

        // Front Arm
        ctx.beginPath();
        ctx.moveTo(12, 32);
        if (isLight) {
            ctx.lineTo(30, 32);
            ctx.lineTo(44, 32); // Thrusting punch / kunai
        } else if (isHeavy) {
            ctx.lineTo(25, 15);
            ctx.lineTo(40, 20);
        } else {
            ctx.lineTo(18 + armSwing * 0.5, 48);
            ctx.lineTo(20, 60);
        }
        ctx.stroke();

        // Kunai / Sword in hand
        ctx.fillStyle = '#b0bec5';
        if (isLight) {
            ctx.beginPath();
            ctx.moveTo(42, 30);
            ctx.lineTo(58, 32);
            ctx.lineTo(42, 34);
            ctx.fill();
        }

        // Head
        ctx.fillStyle = '#ffcc80'; // Skin tone
        ctx.beginPath();
        ctx.arc(0, 14, 13, 0, Math.PI * 2);
        ctx.fill();

        // Hair & Headband
        if (this.id === 'naruto') {
            // Yellow spiky hair
            ctx.fillStyle = '#ffd600';
            ctx.beginPath();
            ctx.moveTo(-14, 10);
            ctx.lineTo(-18, -4);
            ctx.lineTo(-8, 2);
            ctx.lineTo(-2, -8);
            ctx.lineTo(5, 2);
            ctx.lineTo(12, -6);
            ctx.lineTo(16, 8);
            ctx.fill();
        } else if (this.id === 'sasuke') {
            // Dark spiky hair
            ctx.fillStyle = '#1a1a2e';
            ctx.beginPath();
            ctx.moveTo(-15, 12);
            ctx.lineTo(-20, -5);
            ctx.lineTo(-8, 0);
            ctx.lineTo(0, -9);
            ctx.lineTo(10, 0);
            ctx.lineTo(20, -4);
            ctx.lineTo(16, 12);
            ctx.fill();
        } else if (this.id === 'kakashi') {
            // Silver spiky hair & mask
            ctx.fillStyle = '#cfd8dc';
            ctx.beginPath();
            ctx.moveTo(-14, 12);
            ctx.lineTo(-22, -6);
            ctx.lineTo(-6, -2);
            ctx.lineTo(4, -12);
            ctx.lineTo(12, -4);
            ctx.lineTo(18, 6);
            ctx.fill();
            // Ninja face mask
            ctx.fillStyle = '#263238';
            ctx.fillRect(-10, 14, 20, 13);
        } else if (this.id === 'itachi') {
            // Long black hair
            ctx.fillStyle = '#1e1e1e';
            ctx.beginPath();
            ctx.moveTo(-14, 12);
            ctx.lineTo(-16, -2);
            ctx.lineTo(-4, -6);
            ctx.lineTo(6, -6);
            ctx.lineTo(14, -2);
            ctx.lineTo(14, 25);
            ctx.lineTo(-14, 25);
            ctx.fill();
        }

        // Konoha Headband
        ctx.fillStyle = '#263238';
        ctx.fillRect(-12, 5, 24, 7);
        ctx.fillStyle = '#cfd8dc';
        ctx.fillRect(-6, 6, 12, 5); // Silver metal plate

        // Glowing Ninja Eyes
        ctx.fillStyle = (this.id === 'sasuke' || this.id === 'itachi') ? '#d50000' : '#0288d1';
        ctx.beginPath();
        ctx.arc(4, 14, 2.5, 0, Math.PI * 2);
        ctx.fill();

        // Hurt / Dead State Expression
        if (isHurt || isDead) {
            ctx.strokeStyle = '#d50000';
            ctx.lineWidth = 2;
            ctx.beginPath();
            ctx.moveTo(-6, 20);
            ctx.lineTo(6, 20);
            ctx.stroke();
        }
    }
}

// --- PROJECTILE & SUMMON CLASSES ---

// 1. Naruto: Shadow Clone
class ShadowClone {
    constructor(x, y, dir, power) {
        this.x = x;
        this.y = y;
        this.dir = dir;
        this.power = power;
        this.speed = 10;
        this.life = 0.55;
        this.isFinished = false;
        this.width = 50;
        this.height = 90;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        this.x += this.dir * this.speed;

        if (this.life <= 0) {
            this.isFinished = true;
            particleSys.createSmokePuff(this.x, this.y + 40, 10);
            return;
        }

        // Strike opponent
        if (opponent && !opponent.isDead()) {
            const hit = Math.abs(this.x - opponent.x) < 50 && Math.abs(this.y - opponent.y) < 70;
            if (hit) {
                soundCtrl.playHit(false);
                particleSys.createHitSparks(this.x, this.y + 40, '#ff9800', 12);
                opponent.hp = Math.max(0, opponent.hp - 60 * this.power);
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, '60 (BUNSHIN)');
                opponent.vx = this.dir * 8;
                this.isFinished = true;
                particleSys.createSmokePuff(this.x, this.y + 40, 12);
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.globalAlpha = 0.85;
        ctx.translate(this.x, this.y);
        ctx.scale(this.dir, 1);
        ctx.fillStyle = '#ff9800';
        ctx.roundRect(-15, 20, 30, 40, 5);
        ctx.fill();
        ctx.fillStyle = '#ffcc80';
        ctx.beginPath();
        ctx.arc(0, 10, 11, 0, Math.PI * 2);
        ctx.fill();
        ctx.fillStyle = '#ffd600';
        ctx.fillRect(-10, 0, 20, 6);
        ctx.restore();
    }
}

// 2. Sasuke: Fireball Jutsu (Katon: Goukakyuu)
class Fireball {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.dir = dir;
        this.damage = damage;
        this.speed = 9;
        this.radius = 24;
        this.life = 1.4;
        this.isFinished = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        this.x += this.dir * this.speed;
        this.radius = Math.min(45, this.radius + 0.35);

        // Emit fire particles
        particleSys.createChakraFlame(this.x, this.y, '#ff3d00', this.dir * 2);

        if (this.life <= 0 || this.x < 0 || this.x > 1200) {
            this.isFinished = true;
            return;
        }

        // Impact detection
        if (opponent && !opponent.isDead() && opponent.invulnerableTime <= 0) {
            const dist = Math.hypot(this.x - (opponent.x + opponent.width / 2), this.y - (opponent.y + opponent.height / 2));
            if (dist < this.radius + 30) {
                this.isFinished = true;
                soundCtrl.playHit(true);
                particleSys.createHitSparks(this.x, this.y, '#ff3d00', 25);
                opponent.hp = Math.max(0, opponent.hp - this.damage);
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, Math.round(this.damage) + ' (KATON)', true);
                opponent.vx = this.dir * 12;
                opponent.hitStun = 0.35;
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y);
        ctx.shadowColor = '#ff3d00';
        ctx.shadowBlur = 25;

        const grad = ctx.createRadialGradient(0, 0, 4, 0, 0, this.radius);
        grad.addColorStop(0, '#ffffff');
        grad.addColorStop(0.3, '#ffeb3b');
        grad.addColorStop(0.7, '#ff5722');
        grad.addColorStop(1, 'rgba(213, 0, 0, 0.8)');

        ctx.fillStyle = grad;
        ctx.beginPath();
        ctx.arc(0, 0, this.radius, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
    }
}

// 3. Naruto: Rasenshuriken (Ultimate)
class Rasenshuriken {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.dir = dir;
        this.damage = damage;
        this.speed = 10;
        this.radius = 45;
        this.angle = 0;
        this.life = 1.6;
        this.isFinished = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        this.x += this.dir * this.speed;
        this.angle += 0.4;

        particleSys.createChakraFlame(this.x, this.y, '#00e5ff', 0);

        if (this.life <= 0 || this.x < 0 || this.x > 1200) {
            this.isFinished = true;
            return;
        }

        if (opponent && !opponent.isDead()) {
            const dist = Math.hypot(this.x - (opponent.x + opponent.width / 2), this.y - (opponent.y + opponent.height / 2));
            if (dist < this.radius + 30) {
                this.isFinished = true;
                soundCtrl.playHit(true);
                particleSys.createHitSparks(this.x, this.y, '#00e5ff', 35);
                opponent.hp = Math.max(0, opponent.hp - this.damage);
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, Math.round(this.damage) + ' (RASENSHURIKEN)', true);
                opponent.vx = this.dir * 20;
                opponent.vy = -10;
                opponent.hitStun = 0.55;
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y);
        ctx.rotate(this.angle);
        ctx.shadowColor = '#00e5ff';
        ctx.shadowBlur = 30;

        // 4 Wind Shuriken Blades
        for (let i = 0; i < 4; i++) {
            ctx.save();
            ctx.rotate((Math.PI / 2) * i);
            ctx.fillStyle = 'rgba(224, 247, 250, 0.9)';
            ctx.beginPath();
            ctx.moveTo(0, 0);
            ctx.lineTo(this.radius, -12);
            ctx.lineTo(this.radius * 1.3, 0);
            ctx.lineTo(this.radius, 12);
            ctx.closePath();
            ctx.fill();
            ctx.restore();
        }

        // Central Rasengan Sphere
        ctx.fillStyle = '#ffffff';
        ctx.beginPath();
        ctx.arc(0, 0, 18, 0, Math.PI * 2);
        ctx.fill();

        ctx.restore();
    }
}

// 4. Sasuke: Kirin Thunder God (Ultimate)
class KirinDragon {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.dir = dir;
        this.damage = damage;
        this.life = 0.8;
        this.isFinished = false;
        this.hasHit = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        // Thunder strikes ground
        particleSys.createLightning(this.x, 0, this.x + (Math.random() - 0.5) * 40, 480, '#b388ff');

        if (!this.hasHit && opponent && !opponent.isDead()) {
            if (Math.abs(opponent.x + opponent.width / 2 - this.x) < 140) {
                this.hasHit = true;
                soundCtrl.playHit(true);
                particleSys.createHitSparks(this.x, 460, '#b388ff', 40);
                opponent.hp = Math.max(0, opponent.hp - this.damage);
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, Math.round(this.damage) + ' (KIRIN)', true);
                opponent.vy = -12;
                opponent.hitStun = 0.6;
            }
        }

        if (this.life <= 0) this.isFinished = true;
    }

    render(ctx) {
        // Dramatic Kirin storm lightning flash
        ctx.save();
        ctx.fillStyle = 'rgba(124, 77, 255, 0.18)';
        ctx.fillRect(0, 0, 1200, 600);
        ctx.restore();
    }
}

// 5. Kakashi: Earth Style Mud Wall
class EarthWall {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.dir = dir;
        this.damage = damage;
        this.life = 2.0;
        this.height = 100;
        this.width = 40;
        this.isFinished = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        if (this.life <= 0) {
            this.isFinished = true;
            particleSys.createSmokePuff(this.x, this.y, 8);
            return;
        }

        if (opponent && !opponent.isDead()) {
            if (Math.abs(this.x - (opponent.x + opponent.width / 2)) < 35 && Math.abs(this.y - opponent.y) < 60) {
                opponent.hp = Math.max(0, opponent.hp - this.damage * 0.4 * dt);
                opponent.vx = this.dir * 4;
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.fillStyle = '#6d4c41';
        ctx.strokeStyle = '#3e2723';
        ctx.lineWidth = 3;
        ctx.fillRect(this.x - 20, this.y - 40, this.width, this.height);
        ctx.strokeRect(this.x - 20, this.y - 40, this.width, this.height);
        // Dog faces carving on mud wall
        ctx.fillStyle = '#d7ccc8';
        ctx.fillRect(this.x - 12, this.y - 20, 10, 10);
        ctx.fillRect(this.x + 2, this.y - 20, 10, 10);
        ctx.restore();
    }
}

// 6. Kakashi: Kamui Dimension Vortex
class KamuiVortex {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.damage = damage;
        this.life = 1.5;
        this.angle = 0;
        this.radius = 65;
        this.isFinished = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        this.angle += 0.35;

        if (this.life <= 0) {
            this.isFinished = true;
            return;
        }

        // Pull opponent into vortex
        if (opponent && !opponent.isDead()) {
            const dx = this.x - (opponent.x + opponent.width / 2);
            const dist = Math.abs(dx);
            if (dist < 150) {
                opponent.x += Math.sign(dx) * 4;
                opponent.hp = Math.max(0, opponent.hp - this.damage * dt * 0.7);
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, 'KAMUI', true);
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y);
        ctx.rotate(this.angle);
        ctx.shadowColor = '#000000';
        ctx.shadowBlur = 30;

        const grad = ctx.createRadialGradient(0, 0, 5, 0, 0, this.radius);
        grad.addColorStop(0, '#000000');
        grad.addColorStop(0.5, '#d50000');
        grad.addColorStop(1, 'transparent');

        ctx.fillStyle = grad;
        ctx.beginPath();
        ctx.arc(0, 0, this.radius, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
    }
}

// 7. Itachi: Crow Flock
class CrowFlock {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.dir = dir;
        this.damage = damage;
        this.life = 0.8;
        this.isFinished = false;
        this.crows = [];
        for (let i = 0; i < 8; i++) {
            this.crows.push({
                ox: (Math.random() - 0.5) * 50,
                oy: (Math.random() - 0.5) * 50,
                wing: 0
            });
        }
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        this.x += this.dir * 12;

        if (this.life <= 0) {
            this.isFinished = true;
            return;
        }

        if (opponent && !opponent.isDead()) {
            if (Math.abs(this.x - opponent.x) < 50) {
                soundCtrl.playHit(false);
                opponent.hp = Math.max(0, opponent.hp - this.damage);
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, Math.round(this.damage) + ' (CROWS)');
                opponent.hitStun = 0.3;
                this.isFinished = true;
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y);
        ctx.fillStyle = '#111111';
        for (let crow of this.crows) {
            ctx.beginPath();
            ctx.arc(crow.ox, crow.oy, 6, 0, Math.PI * 2);
            ctx.fill();
        }
        ctx.restore();
    }
}

// 8. Itachi: Amaterasu Black Flames
class AmaterasuFlame {
    constructor(x, y, dir, damage) {
        this.x = x;
        this.y = y;
        this.damage = damage;
        this.life = 2.2;
        this.isFinished = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        particleSys.createChakraFlame(this.x, this.y + 30, '#111111', 0);
        particleSys.createChakraFlame(this.x, this.y + 30, '#7c4dff', 0);

        if (this.life <= 0) {
            this.isFinished = true;
            return;
        }

        if (opponent && !opponent.isDead()) {
            if (Math.abs(this.x - (opponent.x + opponent.width / 2)) < 55) {
                opponent.hp = Math.max(0, opponent.hp - this.damage * dt * 0.85);
                opponent.hitStun = 0.1;
                particleSys.addDamageNumber(opponent.x + 20, opponent.y, 'AMATERASU', true);
            }
        }
    }

    render(ctx) {
        ctx.save();
        ctx.translate(this.x, this.y + 30);
        ctx.fillStyle = 'rgba(20, 20, 20, 0.9)';
        ctx.shadowColor = '#d50000';
        ctx.shadowBlur = 20;
        ctx.beginPath();
        ctx.ellipse(0, 0, 35, 60, 0, 0, Math.PI * 2);
        ctx.fill();
        ctx.restore();
    }
}

// 9. Itachi: Tsukuyomi Dimension (Ultimate)
class TsukuyomiDimension {
    constructor(x, y, dir, damage) {
        this.damage = damage;
        this.life = 1.2;
        this.isFinished = false;
        this.hasHit = false;
    }

    update(dt, opponent, particleSys, soundCtrl) {
        this.life -= dt;
        if (!this.hasHit && opponent && !opponent.isDead()) {
            this.hasHit = true;
            opponent.hp = Math.max(0, opponent.hp - this.damage);
            opponent.hitStun = 0.8;
            particleSys.addDamageNumber(opponent.x + 20, opponent.y, Math.round(this.damage) + ' (TSUKUYOMI)', true);
        }
        if (this.life <= 0) this.isFinished = true;
    }

    render(ctx) {
        // Red Tsukuyomi Blood Moon Dimension overlay
        ctx.save();
        ctx.fillStyle = 'rgba(183, 28, 28, 0.35)';
        ctx.fillRect(0, 0, 1200, 600);

        // Giant Blood Moon
        ctx.fillStyle = 'rgba(255, 23, 68, 0.85)';
        ctx.shadowColor = '#ff1744';
        ctx.shadowBlur = 40;
        ctx.beginPath();
        ctx.arc(600, 180, 80, 0, Math.PI * 2);
        ctx.fill();

        ctx.restore();
    }
}

window.Fighter = Fighter;
